#!/bin/bash





function get_cas_ip {
   export CAS_IP=`ping -c1 -n $CAS_NAME  | head -n1 | sed "s/.*(\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\)).*/\1/g" `
 }
 

set -e

# Manual Test
# sh hooks/set-mariadb-node publish-mariadb mariadb andrewklau GEAR-DNS:MYSQL-PORT:GALERA-PORT:SST-PORT

#app_name=$1
#namespace=$2
#local_gear=$3
echo "$@"  >> $OPENSHIFT_MARIADB_DIR/hook-log
 

 
CAS_NAME=`cat hook-log | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 1`
CAS_PORT=`cat hook-log | sed "s/'//g" | grep -m 1 -o 'OPENSHIFT_CAS_NODE_FROM_STORAGE=.*' | cut -d '=' -f 2 | cut -d ':' -f 2`
get_cas_ip

# lets update the scaledb.cnf file
sed -e "s|OPENSHIFT_MARIADB_DB_HOST|${CAS_IP}|" ${OPENSHIFT_MARIADB_DIR}/bin/scaledb.cnf.tmp > ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf.tmp2
sed -e "s|OPENSHIFT_CAS_PORT|${CAS_PORT}|" ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf.tmp2 > ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf
cp ${OPENSHIFT_MARIADB_DIR}/scaledb.cnf ${OPENSHIFT_SCALEDB_MARIA_INSTALL_DIR}/data/


export running=`pgrep mysqld`

echo $running > t87

if [ -z "$running"]
then
echo "MYSQLD not running" + $running
    export LD_LIBRARY_PATH="${OPENSHIFT_SCALEDB_INSTALL_DIR}/lib"
    ${OPENSHIFT_SCALEDB_MARIA_INSTALL_DIR}/bin/mysqld --defaults-file=${OPENSHIFT_MARIADB_DIR}/config.cnf > t3.txt 2>&1 &
    sleep 10
    ${OPENSHIFT_SCALEDB_MARIA_INSTALL_DIR}/bin/mysql -uroot -e "INSTALL PLUGIN scaledb SONAME 'ha_scaledb.so'"





source $OPENSHIFT_CARTRIDGE_SDK_BASH

dbname=$OPENSHIFT_APP_NAME
socket_file=$OPENSHIFT_MARIADB_DB_SOCKET
username=$OPENSHIFT_MARIADB_DB_USERNAME
password=$OPENSHIFT_MARIADB_DB_PASSWORD

# TODO: Should be we running mysql_secure_installation
echo "GRANT ALL ON *.* to root@'%'; flush privileges;" | ${OPENSHIFT_SCALEDB_MARIA_INSTALL_DIR}/bin/mysql -uroot > /dev/null || error "Failed to setup initial root user" 187




fi




echo $CAS_NAME > t88
echo $CAS_IP > t89
echo $CAS_PORT > t90

